### ISSUE TITLE
Published package

### ISSUE THREAD

**Issue by maxhille** [elm-scotland/elm-toml#1]
Is there a reason this package is not published at package.elm-lang.org?

As far as I can tell this might be the only TOML library for Elm 0.19...

**Comment by TSFoster** [comment]
This is very, very far from being close to useful. We picked it as a group project to work on in monthly meetups, specifically because none of us needed it (so nobody was tempted to work between meetings). Unfortunately we only worked on it once or twice before the pandemic hit, and we've not had any meetups since.

**Comment by maxhille** [comment]
Thanks for the quick reply. Sounds like I'll have to wait a while for a proper package then ;-)

And I feel you, Meetups in my area have been completely - like 100% - purged by the pandemic. So I hope you can reboot yours!
